---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: nginx
  namespace: default
spec:
  url: https://github.com/pizicaiman/fleet-infra
  ref: 
    branch: main
  interval: 10s
